### ISSUE TITLE
Nem így nézzük meg a pinget

### ISSUE THREAD

**Issue by Bendimester23** [blazsmaster/discord-super-mod-bot#1]
.addField('Bot latency', `${Math.round(message.createdTimestamp / 10000000000)}ms`)
ez nem fog működni, mert ez csak az üzenet küldésekori időt mutatja. neked a bot.ws.ping kell ami a websocket pinget adja ki. a te megoldásod férrevezető, és az idő múlásával egyre többet mutat.

**Comment by blazsmaster** [comment]
Oh... Köszönöm, hogy szóltál Bendimester23! Hamarosan kijavítom.

**Comment by blazsmaster** [comment]
Rendben! Köszönöm hogy szóltál! Hamarosan ki lesz javítva...
